{% set name = "libqdldl" %}
{% set version = "0.1.8" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/osqp/qdldl/archive/v{{ version }}.tar.gz
  sha256: ecf113fd6ad8714f16289eb4d5f4d8b27842b6775b978c39def5913f983f6daa

build:
  number: 0
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x.x') }}

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja-base

test:
  commands:
    - test -f ${PREFIX}/include/qdldl/qdldl.h  # [not win]
    - test -f ${PREFIX}/lib/libqdldl${SHLIB_EXT}  # [not win]
    - test ! -f ${PREFIX}/lib/libqdldl.a  # [not win]
    - test -f ${PREFIX}/lib/cmake/qdldl/qdldl-config.cmake  # [not win]
    - if not exist %PREFIX%\\Library\\include\\qdldl\\qdldl.h exit 1  # [win]
    - if not exist %PREFIX%\\Library\\bin\\qdldl.dll exit 1  # [win]
    - if not exist %PREFIX%\\Library\\lib\\cmake\\qdldl\\qdldl-config.cmake exit 1  # [win]

about:
  home: https://github.com/osqp/qdldl
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: A free LDL factorisation routine for quasi-definite linear systems.
  description: A free LDL factorisation routine for quasi-definite linear systems.
  dev_url: https://github.com/osqp/qdldl
  doc_url: https://github.com/osqp/qdldl/blob/master/README.md

extra:
  recipe-maintainers:
    - traversaro
    - h-vetinari
